[package]
name = "repos"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"
overflow-checks = true

# Run strip on the binary!
# $ string ./target/release/...
