name: Python Pytest testing template

on: push

jobs:

  test:

    runs-on: ubuntu-20.04
    timeout-minutes: 15

    steps:
      - name: actions/checkout@v2
        uses: actions/checkout@v2

      - name: actions/setup-python@v2
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pipenv
        run: python -m pip install --upgrade pipenv wheel

      - name: Install dependencies
        run: python -m pipenv install --dev

      - name: Run tests
        run: pipenv run pytest -svvv

